name: Deploy to GitHub Pages

on:
  push:
    branches: main
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x.x'

    - name: Change base tag in index.html from / to TryDotNet
      run: sed -i 's/<base href="\/" \/>/<base href="\/TryDotNet\/" \/>/g' wwwroot/index.html

    - name: Change base tag in Program.cs from / to TryDotNet
      run: sed -i 's/const string baseTag = "\/"/const string baseTag = "\/TryDotNet\/"/g' Program.cs
        
    - name: Publish .NET Core Project
      run: dotnet publish InterviewDotNet.sln -c Release --output release --nologo
      
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot
